### ISSUE TITLE
Add a new Performance setting to disable DimGen animations 

### ISSUE THREAD

**Issue by grabz-dev** [Trimps/bug-tracker#23]
**Is your feature request related to a problem? Please describe.**
DimGen animations, such as the moving gauge, or fuel animations, cause the game to go into high FPS mode when they are active.

**Describe the solution you'd like**
It would be nice to have a performance setting to turn them off, to prevent the above from happening.
This can be solved with the following CSS, but it would be nice that non power users could access the option:
```css
#generatorRadial {
   display: none;
}

#fuelStorageBar {
   transition: none;
}
```
